version: '3.8'

services:
  malmo-blue:
    image: ${DOCKERHUB_USERNAME}/malmo-app:latest
    container_name: malmo-blue
    depends_on:
      - redis
    ports:
      - "8081:8080"
    networks:
      - malmo-network
    restart: always
    env_file:
      - ./.env

  malmo-green:
    image: ${DOCKERHUB_USERNAME}/malmo-app:latest
    container_name: malmo-green
    depends_on:
      - redis
    ports:
      - "8082:8080"
    networks:
      - malmo-network
    restart: always
    env_file:
      - ./.env

  redis:
    image: "redis:7-alpine"
    container_name: malmo-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - malmo-network
    restart: always

networks:
  malmo-network:
    driver: bridge

volumes:
  redis-data:
