spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    makeus.cmc.malmo: DEBUG

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-seconds: 3600
  refresh-token-expiration-seconds: 86400

kakao:
  oidc:
    iss: https://kauth.kakao.com
    aud: ${KAKAO_REST_API_KEY}
    jwks-uri: https://kauth.kakao.com/.well-known/jwks.json
    user-info-uri: https://kapi.kakao.com/v1/oidc/userinfo

apple:
  oidc:
    iss: https://appleid.apple.com
    aud: ${APPLE_REST_API_KEY}
    jwks-uri: https://appleid.apple.com/auth/keys