spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:data-test.sql
  data:
    redis:
      port: 6379
      host: localhost
      stream-key: test-stream
      consumer-group: test-group
      repositories:
        enabled: false


server:
  servlet:
    encoding:
      force-response: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG

jwt:
  secret: test-jwt-secret-key-for-testing-only
  access-token-expiration-seconds: 3600
  refresh-token-expiration-seconds: 86400

kakao:
  oidc:
    iss: https://kauth.kakao.com
    aud: test-kakao-client-id
    jwks-uri: https://kauth.kakao.com/.well-known/jwks.json
    user-info-uri: https://kapi.kakao.com/v1/oidc/userinfo
  oauth:
    unlink-uri: https://kapi.kakao.com/v1/user/unlink
    admin-key: test-kakao-admin-key

apple:
  oidc:
    iss: https://appleid.apple.com
    aud: test-apple-client-id
    jwks-uri: https://appleid.apple.com/auth/keys
  oauth:
    team-id: test-apple-team-id
    client-id: com.malmo.app
    key-id: test-apple-key-id
    private-key: test-apple-private-key
    revoke-uri: https://appleid.apple.com/auth/revoke
    token-uri: https://appleid.apple.com/auth/token

swagger:
  server:
    production:
      url: sample.url.com

openai:
  api:
    key: sk-test-openai-api-key-for-testing-only

security:
  server:
    url:
      production: test.server.com
      development: test.server.dev.com
  client:
    url:
      production: test.prod.com
      development:  test.dev.com

encryption:
  aes:
    key: testaeskeyrZktAgxX77DA==
