spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

sql:
  init:
    mode: never

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG

jwt:
  secret: test-jwt-secret-key-for-testing-only
  access-token-expiration-seconds: 3600
  refresh-token-expiration-seconds: 86400

kakao:
  oidc:
    iss: https://kauth.kakao.com
    aud: test-kakao-client-id
    jwks-uri: https://kauth.kakao.com/.well-known/jwks.json
    user-info-uri: https://kapi.kakao.com/v1/oidc/userinfo

apple:
  oidc:
    iss: https://appleid.apple.com
    aud: test-apple-client-id
    jwks-uri: https://appleid.apple.com/auth/keys

swagger:
  server:
    production:
      url: sample.url.com

openai:
  api:
    key: sk-test-openai-api-key-for-testing-only