spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-seconds: 3600
  refresh-token-expiration-seconds: 86400

logging:
  level:
    makeus.cmc.malmo: DEBUG

kakao:
  oidc:
    iss: https://kauth.kakao.com
    aud: ${KAKAO_REST_API_KEY}
    jwks-uri: https://kauth.kakao.com/.well-known/jwks.json
    user-info-uri: https://kapi.kakao.com/v1/oidc/userinfo

apple:
  oidc:
    iss: https://appleid.apple.com
    aud: ${APPLE_REST_API_KEY}
    jwks-uri: https://appleid.apple.com/auth/keys

swagger:
  server:
    production:
      url: ${SWAGGER_SERVER_PRODUCTION_URL}